services:
  api:
    # الخيار 1: إذا رفعت الصورة على Docker Hub (أنصح به)
    image: engcryo/wasl-api:v1

    # الخيار 2: إذا نقلت ملفات الكود للسيرفر وتريد البناء هناك (احذف السطر فوق وفعل هذا)
    # build: .

    container_name: wasl-api
    restart: always
    ports:
      - "80:8080"  # يربط بورت 80 في السيرفر ببورت 8080 في التطبيق
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - EnableScalar=true
      # هنا السحر: ضع الـ Private IP الخاص بالسيرفر الأول (A)
      - ConnectionStrings__DefaultConnection=Host=10.0.0.84;Port=5432;Database=TestDb;Username=Cryo;Password=Cryo4Cryo@123